version: '3.8'
services:
  nest:
    container_name: nest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      POSTGRES_HOST: postgres:root@postgres:5432
      PORT: 3000

    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 54321:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest-boilerplate
